### ISSUE TITLE
Change font size in yaml 

### ISSUE THREAD

**Issue by danielrak** [bbucior/drposter#11]
Hello, 

How one change the font via yaml ? 

« fontsize : 14pt » or « font-size : 14pt » or « font_size : 14pt » do not seem to work. 

I am a beginner, sorry if the answer is an obvious one.

Respects.

**Comment by bbucior** [comment]
It is not currently possible via the yaml since there are so many styles you could potentially customize. The font sizes are currently hardcoded in the package's fonts.css, but you can override the default styles using the custom.css file (provided the custom.css line is specified in the yaml header).  For example, you could add the following to custom.css:

```
html {
  font-size: 14pt;
}

h1, h2 {
  font-size: 20pt;
}
```

Does that help?

**Comment by danielrak** [comment]
Re, 

I am thankfull for your response. 

should I place the custom.css file in the drposter_files folder or in the R session working directory ?

Thanks
