### ISSUE TITLE
Spacing around equations

### ISSUE THREAD

**Issue by FrankD** [bbucior/drposter#3]
Spacing around equations seems to be off; inline equations result in extra space between the line of text that contains the equation and the preceding text, while stand-alone equations seem to have extra space inserted to separate them from the previous block of text. Any ideas for a work-around?

**Comment by FrankD** [comment]
It seems to be a MathJax issue rather than a drposter issue; will close the issue, but happy to hear if you can think of any solutions.

**Comment by bbucior** [comment]
One of my posters had this issue, too, but I haven't figured out the root cause or incompatibility with MathJax.  It looks like I got around the inline issue by rephrasing the text to put the inline equation at the end of the sentence instead of within.  To get around the standalone equation spacing, I ended up overriding the CSS:

```
<div class="fulleqn" style="margin-top:0;">$$
y = 28  \color{#4D0C6B}{- 184 x_\text{something}} \color{#9E2A63}{+ 52.6 \cdots}
$$</div>
```

Neither of these are great, and a permanent fix would be a lot better.
